version: '2'
services:
  web:
    build: ./web
    command: ["/bin/bash", "/app/start.sh"]
    restart: always
    networks:
      - nginx
    volumes:
      - ./web:/app/

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8443:443"
    networks:
      - nginx
    depends_on:
      - web

networks:
  nginx:
