version: '2'
services:
  web:
    build: ./web
    command: ["uwsgi", "--socket=:3031", "--processes=1", "--harakiri=60", "--max-requests=10000", "--post-buffering=8192", "--wsgi-file=/app/project/wsgi.py", "--master", "--pidfile=/tmp/uwsgi.pid", "--vacuum", "--die-on-term", "--disable-logging", "--logdate", "--log-5xx", "--log-slow=5000", "--py-autoreload=1"]
    restart: always
    networks:
      - nginx
    volumes:
      - ./web:/app/

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8443:443"
    networks:
      - nginx
    depends_on:
      - web

networks:
  nginx:
