# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zabbix_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
